# -*- coding: utf-8 -*-
#
# Copyright (c) 2021~2999 - Cologler <skyoflw@gmail.com>
# ----------
#
# ----------

class FrameworkException(Exception): ...

class UnauthorizedException(Exception): ...

class BadRequestException(Exception): ...

class AttributeException(Exception): ...

class RedirectError(Exception):
    code: int
    headers: dict
    @property
    def location(self) -> str: ...

class PlexError(Exception): ...

class PlexNonCriticalError(PlexError): ...

class MediaNotAvailable(PlexNonCriticalError): ...

class MediaExpired(PlexNonCriticalError): ...

class LiveMediaNotStarted(PlexNonCriticalError): ...

class MediaNotAuthorized(PlexNonCriticalError): ...

class MediaGeoblocked(PlexNonCriticalError): ...

class StreamLimitExceeded(PlexNonCriticalError): ...

class AttributeTypeMismatch(PlexError): ...

class ContextException(PlexError): ...

class APIException(PlexError): ...

class NonCriticalArgumentException(PlexNonCriticalError): ...
